### PR TITLE
User agent update to match new insta settings

### PR DESCRIPTION
**Pull request by suxSx**
New instagram settings gives Error on string: https://i.instagram.com/api/v1/friendships/create/13960577847/ - get info JSON

ERROR: {"message": "useragent mismatch", "status": "fail"}

Need to use a official useragent for endpoint to work.

### CODE REVIEW

**Comment by instasck** [comment]
will this solve some blocks I get on 4g proxy with no login user?
instead of public page Info I get:
{'config': {'csrf_token': 'wMbBUf9LOfSxKY7CvdrbHlKLsyyoZ3gT', 'viewer': None, 'viewerId': None}, 'country_code': 'IL', 'language_code': 'en', 'locale': 'en_US', 'entry_data': {'LoginAndSignupPage': [{'captcha': {'enab

So I guess it blocks me.

**Comment by suxSx** [comment]
I don't thinl it will fix your problem. It looks like it is bevause of your request to the server. But it's worth a try. If you could send me the log of action you do when I happen and error log I would like to take a look at it.

**Comment by sionking** [comment]
so I rotate my 120 4g proxies with 5 most common user agent and it seems to work now

**Comment by suxSx** [comment]
That great to know. Thanks. 😊

**Pull request closed without merging**
