### PR TITLE
Set user agent

### PR DESCRIPTION
**Pull request by NMelis**

### CODE REVIEW

**Comment by NMelis** [comment]
@realsirjoe why don't you accept my pull requests?

**Comment by NMelis** [comment]
*last pull requests

**Comment by oneEyedSunday** [comment]
@NMelis your pull requests now have conflicts. I suggest you update it.

**Comment by NMelis** [comment]
for this it was necessary to take 3 days ago, when there was no conflict (

**Comment by realsirjoe** [comment]
I am sorry for that but at that time I already worked on merging with luengwaiban's project

**Comment by luengwaiban** [comment]
@NMelis can you fix some code change that cause by formatting like ?
image
thank you~

**Comment by NMelis** [comment]
send new pull request https://github.com/realsirjoe/instagram-scraper/pull/17

**Pull request closed without merging**
