### PR TITLE
Used requests_html.HTMLSession instead of requests.session to overcome <Response 429> issue

### PR DESCRIPTION
**Pull request by Siyam1888**
### Recently the instagram scraper's get_medias method and some other methods stopped working due to some header related problems

> I found it to be fixed by using `requests_html.HTMLSession` instead of `requests.session `

> I have tested the example files and most of them are working now even without user logins

> I have also changed some of the example files to make them work but did not include in this pull request.

### Changes made:
- using `requests_html.HTMLSession` instead of `requests.session `
- installing `requests_html` and packages with it
- updating the `requirements.txt` file

### CODE REVIEW

**Comment by JoseRa9** [comment]
Nice. Log In is now working but the comments related methods are still broken, Did you fix it?

**Comment by Avataar120** [comment]
Hi,
Thx for your work and sharing.
On my side, I still have a request for two-factors authent each time I try to log in.
Do you have the same issue ?

Thx.

**Comment by Siyam1888** [comment]
Hello,
@Avataar120, Actually I did not try it with two-factor authentication, so I can not say anything about it.

thanks.

**Comment by Riverfount** [comment]
> @JoseRa9 , Actually I was working with user and post data, so I did not focus on comments .

Are there any plans to solve the comments problem?

**Comment by danwyryunq** [comment]
This fix solved the problem for me too.

**Comment by luengwaiban** [comment]
@Siyam1888  thanks

**Comment by fettay** [comment]
Nice fix thanks @Siyam1888 
I recommend updating the pip package.

**Comment by ShaunGee** [comment]
Thanks!

**Pull request merged**
